export const RECOMMENDATIONS_ARE_LOADING = "RECOMMENDATIONS_ARE_LOADING";
export const RECOMMENDATIONS_ARE_NOT_LOADING =
  "RECOMMENDATIONS_ARE_NOT_LOADING";
export const RECOMMENDATIONS_ARE_REFRESHING = "RECOMMENDATIONS_ARE_REFRESHING";
export const RECOMMENDATIONS_ARE_NOT_REFRESHING =
  "RECOMMENDATIONS_ARE_NOT_REFRESHING";
